name: Continuous Integration

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # All history

      - name: Restore dependencies
        run: >
          dotnet restore
          --verbosity minimal

      - name: Build source code
        run: >
          dotnet build
          --no-restore
          --configuration Debug
          --verbosity minimal

      - name: Run unit tests
        run: >
          dotnet test
          --no-build
          --no-restore
          --configuration Debug
          --verbosity minimal
          /p:CollectCoverage=true
          /p:CoverletOutput=../TestResults/
          /p:CoverletOutputFormat=opencover

      - name: Upload test coverage
        uses: codecov/codecov-action@v5
        with:
          name: codecov-umbrella
          directory: ./test/TestResults/
          fail_ci_if_error: true
